trigger:
- master

variables:
  subscription: 'neerajc-service-conn'

stages:
- stage: Development_Stage
  displayName: 'Build the development environment resource group'
  jobs:
  - deployment: DeployDevelopmentGroup
    environment: 'Development'
  - template: 100-resource-group/create-resource-group.yml
    parameters:
      name: create_dev_infra_resource_group
      displayName: '1st Step >> Create resource group for development environment'
      vmImage: 'windows-latest'
      resourceGroupName: neerajc-dev
      subscription: $(subscription)

- stage: Test_Stage
  displayName: 'Build the test environment resource group'
  jobs:
  - deployment: DeployTestGroup
    environment: 'Test'
  - template: 100-resource-group/create-resource-group.yml
    parameters:
      name: create_test_infra_resource_group
      displayName: '1st Step >> Create resource group for test environment'
      vmImage: 'windows-latest'
      resourceGroupName: neerajc-test
      subscription: $(subscription)
  
- stage: PreProduction_Stage
  displayName: 'Build the pre-prod environment resource group'
  jobs:
  - deployment: DeployPreProductionGroup
    environment: 'PreProduction'
  - template: 100-resource-group/create-resource-group.yml
    parameters:
      name: create_preprod_infra_resource_group
      displayName: '1st Step >> Create resource group for pre-production environment'
      vmImage: 'windows-latest'
      resourceGroupName: neerajc-preprod
      subscription: $(subscription)

- stage: Production_Stage
  displayName: 'Build the production environment resource group'
  jobs:
  - deployment: DeployProductionGroup
    environment: 'Production'
  - template: 100-resource-group/create-resource-group.yml
    parameters:
      name: create_prod_infra_resource_group
      displayName: '1st Step >> Create resource group for production environment'
      vmImage: 'windows-latest'
      resourceGroupName: neerajc-prod
      subscription: $(subscription)