trigger:
- master

variables:
  subscription: 'neerajc-service-conn'

stages:
- stage: Development Stage
  displayName: 'Build the development environment resource group'
  jobs:
  - template: 100-resource-group/create-resource-group.yml
    parameters:
      name: create_dev_infra_resource_group
      displayName: '1st Step >> Create resource group for development environment'
      vmImage: 'windows-latest'
      resourceGroupName: neerajc-dev-rg
      subscription: $(subscription)

- stage: Test Stage
  displayName: 'Build the test environment resource group'
  jobs:
  - template: 100-resource-group/create-resource-group.yml
    parameters:
      name: create_test_infra_resource_group
      displayName: '1st Step >> Create resource group for test environment'
      vmImage: 'windows-latest'
      resourceGroupName: neerajc-test-rg
      subscription: $(subscription)
  
- stage: Pre-Production Stage
  displayName: 'Build the pre-prod environment resource group'
  jobs:
  - template: 100-resource-group/create-resource-group.yml
    parameters:
      name: create_preprod_infra_resource_group
      displayName: '1st Step >> Create resource group for pre-production environment'
      vmImage: 'windows-latest'
      resourceGroupName: neerajc-preprod-rg
      subscription: $(subscription)

- stage: Production Stage
  displayName: 'Build the production environment resource group'
  jobs:
  - template: 100-resource-group/create-resource-group.yml
    parameters:
      name: create_prod_infra_resource_group
      displayName: '1st Step >> Create resource group for production environment'
      vmImage: 'windows-latest'
      resourceGroupName: neerajc-prod-rg
      subscription: $(subscription)